#!/bin/sh
#
# Copyright (C) 2013 Opinsys Oy
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

egrep -vr '^\s*#' /etc/dmctab | while read name metadata_dev cache_dev origin_dev block_size rest; do

    dmsetup ls --target cache | egrep -q "^${name}\s+" && {
        echo "W: dmcache '${name}' already exists" >&2
        continue
    }

    origin_dev_size=$(blockdev --getsz "${origin_dev}")
    if [ $? -ne 0 ]; then
	echo "E: failed to get the size of the origin device '${origin_dev}'" >&2
	continue
    fi

    dmsetup create "${name}" \
        --table "0 ${origin_dev_size} cache ${metadata_dev} ${cache_dev} ${origin_dev} ${block_size} ${rest}" || {
        echo "E: failed to load dmcache '${name}'" >&2
	continue
    }

done
