#!/bin/sh
#
# Copyright (C) 2013 Opinsys Oy
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

egrep -vr '^\s*#' /etc/dmctab | while read name metadata_dev cache_dev origin_dev block_size _; do

    dmsetup ls --target cache | egrep -q "^${name}\s+" || {
        echo "W: dmcache '${name}' does not exist" >&2
        continue
    }

    dmsetup suspend "${name}" || {
        echo "E: failed to suspend dmdcache '${name}', perhaps umount it first?" >&2
        continue
    }

    dmsetup reload "${name}" \
        --table "0 ${origin_dev_size} cache ${metadata_dev} ${cache_dev} ${origin_dev} ${block_size} 0 cleaner 0" || {
        echo "E: failed to reload dmcache '${name}' with cleanup policy" >&2
        continue
    }

    dmsetup resume "${name}" || {
        echo "E: failed to resume dmdcache '${name}' with cleanup policy" >&2
        continue
    }

    dmsetup wait "${name}" || {
        echo "E: failed to wait until all dirty blocks of dmcache '${name}' are written to backing volume" >&2
        continue
        
    }

    dmsetup remove "${name}" || {
        echo "E: failed to remove dmcache '${name}'" >&2
        continue
    }

done
